name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - List environment variables (for troubleshooting)
      run: |
        echo "Checking if secrets are available:"
        echo "DOCKERHUB_USERNAME exists: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
        echo "DOCKERHUB_PASSWORD exists: ${{ secrets.DOCKERHUB_PASSWORD != '' }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-for-zerotrust:latest

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-for-zerotrust:latest
        severity: CRITICAL,HIGH
        exit-code: 1

    - name: Deploy to Minikube
      run: |
        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/

        # Configure Minikube (assuming Minikube is accessible via kind or similar)
        eval $(minikube docker-env)  # This step won't work directly; adjust for GitHub Actions
        kubectl apply -f ./app/k8s/deployment.yaml
        kubectl rollout status deployment/static-website
      env:
        KUBECONFIG: ~/.kube/config