name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image and push docker image
      run: docker buildx build app -t docker.io/DOCKER_USERNAME/devsecops-for-zerotrust:latest --push

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/${{ secrets.DOCKER_USERNAME }}/app:latest
        severity: CRITICAL,HIGH

    - name: Push image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/app:latest
